POST http://localhost:8081/go_load.GoLoadService/CreateAccount
Accept: application/json
Content-Type: application/json

{
  "accountName": "khoi123",
  "password": "test123"
}


###CreateSession
POST http://localhost:8081/go_load.GoLoadService/CreateSession
Accept: application/json
Content-Type: application/json

{
  "accountName": "khoi123",
  "password": "test123"
}

###CreateDownloadTask
POST http://localhost:8081/go_load.GoLoadService/CreateDownloadTask
Accept: application/json
Content-Type: application/json
Grpc-Metadata-Goload_auth: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDE5NDI4MjQsImtpZCI6NzgsInN1YiI6MX0.C7DFOTBvHH6zatjIo20rUjeyeYotFOkq350j3-FKq-bDQAFQ1x3R9xCj2uk1kZA1bjwoHq_cZBVXIQwUBIcMIBx1W22POdlag8VUAbOgkLMHFYHt_gjKePzpqysUYsR5o4TS-yto8F7wpopqC-dLmuytL5Ag5ns6oDYAb1XI2l6-UMO85CtcP4kzsEaSfuP1GJ7YKf8dcJKWmDgx_BSQLkptoRcx99wrKmy-GyF1Yz1F0cz8JHPail3pQm0zqpSYhdGIDky1X5Ot1I8y0WBu5iaUzflerGSTZxt55V9pcyedKj30iIEMrNqC3MVhKLb0CA3jhOPD6iplkPA_0GjaWA

{
  "downloadType": 1,
  "url": "https://www.stu.edu.vn/"
}

