POST http://localhost:8081/go_load.GoLoadService/CreateAccount
Accept: application/json
Content-Type: application/json

{
  "accountName": "khoi123",
  "password": "test123"
}


###CreateSession
POST http://localhost:8081/go_load.GoLoadService/CreateSession
Accept: application/json
Content-Type: application/json

{
  "accountName": "khoi123",
  "password": "test123"
}

###CreateDownloadTask
POST http://localhost:8081/go_load.GoLoadService/CreateDownloadTask
Accept: application/json
Content-Type: application/json
Cookie: cookie.txt

{
  "downloadType": 1,
  "url": "https://www.stu.edu.vn/"
}

###
curl -X 'POST' \
'localhost:8081/go_load.GoLoadService/CreateSession' \
    -H 'accept: application/json' \
    -H 'Content-Type: application/json' \
    --cookie-jar cookie.txt \
    -d '{
"accountName": "khoi123",
"password": "test123"
}'


###
curl -X 'POST' \
'http://localhost:8081/go_load.v1.GoLoadService/CreateDownloadTask' \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  --cookie cookie.txt \
  -d '{
  "downloadType": 1,
  "url": "https://example.com"
}'

