/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1Account
 */
export interface V1Account {
    /**
     * 
     * @type {string}
     * @memberof V1Account
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Account
     */
    accountName?: string;
}

/**
 * Check if a given object implements the V1Account interface.
 */
export function instanceOfV1Account(value: object): value is V1Account {
    return true;
}

export function V1AccountFromJSON(json: any): V1Account {
    return V1AccountFromJSONTyped(json, false);
}

export function V1AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Account {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
    };
}

export function V1AccountToJSON(json: any): V1Account {
    return V1AccountToJSONTyped(json, false);
}

export function V1AccountToJSONTyped(value?: V1Account | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'accountName': value['accountName'],
    };
}

