/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CreateAccountRequest
 */
export interface V1CreateAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CreateAccountRequest
     */
    accountName?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateAccountRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the V1CreateAccountRequest interface.
 */
export function instanceOfV1CreateAccountRequest(value: object): value is V1CreateAccountRequest {
    return true;
}

export function V1CreateAccountRequestFromJSON(json: any): V1CreateAccountRequest {
    return V1CreateAccountRequestFromJSONTyped(json, false);
}

export function V1CreateAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function V1CreateAccountRequestToJSON(json: any): V1CreateAccountRequest {
    return V1CreateAccountRequestToJSONTyped(json, false);
}

export function V1CreateAccountRequestToJSONTyped(value?: V1CreateAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountName': value['accountName'],
        'password': value['password'],
    };
}

