/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CreateAccountResponse
 */
export interface V1CreateAccountResponse {
    /**
     * 
     * @type {string}
     * @memberof V1CreateAccountResponse
     */
    accountId?: string;
}

/**
 * Check if a given object implements the V1CreateAccountResponse interface.
 */
export function instanceOfV1CreateAccountResponse(value: object): value is V1CreateAccountResponse {
    return true;
}

export function V1CreateAccountResponseFromJSON(json: any): V1CreateAccountResponse {
    return V1CreateAccountResponseFromJSONTyped(json, false);
}

export function V1CreateAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
    };
}

export function V1CreateAccountResponseToJSON(json: any): V1CreateAccountResponse {
    return V1CreateAccountResponseToJSONTyped(json, false);
}

export function V1CreateAccountResponseToJSONTyped(value?: V1CreateAccountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
    };
}

