/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CreateSessionRequest
 */
export interface V1CreateSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CreateSessionRequest
     */
    accountName?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateSessionRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the V1CreateSessionRequest interface.
 */
export function instanceOfV1CreateSessionRequest(value: object): value is V1CreateSessionRequest {
    return true;
}

export function V1CreateSessionRequestFromJSON(json: any): V1CreateSessionRequest {
    return V1CreateSessionRequestFromJSONTyped(json, false);
}

export function V1CreateSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function V1CreateSessionRequestToJSON(json: any): V1CreateSessionRequest {
    return V1CreateSessionRequestToJSONTyped(json, false);
}

export function V1CreateSessionRequestToJSONTyped(value?: V1CreateSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountName': value['accountName'],
        'password': value['password'],
    };
}

