/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const V1DownloadStatus = {
    DownloadStatusUnspecified: 'DOWNLOAD_STATUS_UNSPECIFIED',
    DownloadStatusPending: 'DOWNLOAD_STATUS_PENDING',
    DownloadStatusDownloading: 'DOWNLOAD_STATUS_DOWNLOADING',
    DownloadStatusFailed: 'DOWNLOAD_STATUS_FAILED',
    DownloadStatusSuccess: 'DOWNLOAD_STATUS_SUCCESS'
} as const;
export type V1DownloadStatus = typeof V1DownloadStatus[keyof typeof V1DownloadStatus];


export function instanceOfV1DownloadStatus(value: any): boolean {
    for (const key in V1DownloadStatus) {
        if (Object.prototype.hasOwnProperty.call(V1DownloadStatus, key)) {
            if (V1DownloadStatus[key as keyof typeof V1DownloadStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function V1DownloadStatusFromJSON(json: any): V1DownloadStatus {
    return V1DownloadStatusFromJSONTyped(json, false);
}

export function V1DownloadStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DownloadStatus {
    return json as V1DownloadStatus;
}

export function V1DownloadStatusToJSON(value?: V1DownloadStatus | null): any {
    return value as any;
}

export function V1DownloadStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): V1DownloadStatus {
    return value as V1DownloadStatus;
}

