/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Account } from './V1Account';
import {
    V1AccountFromJSON,
    V1AccountFromJSONTyped,
    V1AccountToJSON,
    V1AccountToJSONTyped,
} from './V1Account';
import type { V1DownloadType } from './V1DownloadType';
import {
    V1DownloadTypeFromJSON,
    V1DownloadTypeFromJSONTyped,
    V1DownloadTypeToJSON,
    V1DownloadTypeToJSONTyped,
} from './V1DownloadType';
import type { V1DownloadStatus } from './V1DownloadStatus';
import {
    V1DownloadStatusFromJSON,
    V1DownloadStatusFromJSONTyped,
    V1DownloadStatusToJSON,
    V1DownloadStatusToJSONTyped,
} from './V1DownloadStatus';

/**
 * 
 * @export
 * @interface V1DownloadTask
 */
export interface V1DownloadTask {
    /**
     * 
     * @type {string}
     * @memberof V1DownloadTask
     */
    id?: string;
    /**
     * 
     * @type {V1Account}
     * @memberof V1DownloadTask
     */
    ofAccount?: V1Account;
    /**
     * 
     * @type {V1DownloadType}
     * @memberof V1DownloadTask
     */
    downloadType?: V1DownloadType;
    /**
     * 
     * @type {string}
     * @memberof V1DownloadTask
     */
    url?: string;
    /**
     * 
     * @type {V1DownloadStatus}
     * @memberof V1DownloadTask
     */
    downloadStatus?: V1DownloadStatus;
}



/**
 * Check if a given object implements the V1DownloadTask interface.
 */
export function instanceOfV1DownloadTask(value: object): value is V1DownloadTask {
    return true;
}

export function V1DownloadTaskFromJSON(json: any): V1DownloadTask {
    return V1DownloadTaskFromJSONTyped(json, false);
}

export function V1DownloadTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DownloadTask {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'ofAccount': json['ofAccount'] == null ? undefined : V1AccountFromJSON(json['ofAccount']),
        'downloadType': json['downloadType'] == null ? undefined : V1DownloadTypeFromJSON(json['downloadType']),
        'url': json['url'] == null ? undefined : json['url'],
        'downloadStatus': json['downloadStatus'] == null ? undefined : V1DownloadStatusFromJSON(json['downloadStatus']),
    };
}

export function V1DownloadTaskToJSON(json: any): V1DownloadTask {
    return V1DownloadTaskToJSONTyped(json, false);
}

export function V1DownloadTaskToJSONTyped(value?: V1DownloadTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ofAccount': V1AccountToJSON(value['ofAccount']),
        'downloadType': V1DownloadTypeToJSON(value['downloadType']),
        'url': value['url'],
        'downloadStatus': V1DownloadStatusToJSON(value['downloadStatus']),
    };
}

