/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1GetDownloadTaskFileRequest
 */
export interface V1GetDownloadTaskFileRequest {
    /**
     * 
     * @type {string}
     * @memberof V1GetDownloadTaskFileRequest
     */
    downloadTaskId?: string;
}

/**
 * Check if a given object implements the V1GetDownloadTaskFileRequest interface.
 */
export function instanceOfV1GetDownloadTaskFileRequest(value: object): value is V1GetDownloadTaskFileRequest {
    return true;
}

export function V1GetDownloadTaskFileRequestFromJSON(json: any): V1GetDownloadTaskFileRequest {
    return V1GetDownloadTaskFileRequestFromJSONTyped(json, false);
}

export function V1GetDownloadTaskFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetDownloadTaskFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadTaskId': json['downloadTaskId'] == null ? undefined : json['downloadTaskId'],
    };
}

export function V1GetDownloadTaskFileRequestToJSON(json: any): V1GetDownloadTaskFileRequest {
    return V1GetDownloadTaskFileRequestToJSONTyped(json, false);
}

export function V1GetDownloadTaskFileRequestToJSONTyped(value?: V1GetDownloadTaskFileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'downloadTaskId': value['downloadTaskId'],
    };
}

