/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1UpdateDownloadTaskRequest
 */
export interface V1UpdateDownloadTaskRequest {
    /**
     * 
     * @type {string}
     * @memberof V1UpdateDownloadTaskRequest
     */
    downloadTaskId?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateDownloadTaskRequest
     */
    url?: string;
}

/**
 * Check if a given object implements the V1UpdateDownloadTaskRequest interface.
 */
export function instanceOfV1UpdateDownloadTaskRequest(value: object): value is V1UpdateDownloadTaskRequest {
    return true;
}

export function V1UpdateDownloadTaskRequestFromJSON(json: any): V1UpdateDownloadTaskRequest {
    return V1UpdateDownloadTaskRequestFromJSONTyped(json, false);
}

export function V1UpdateDownloadTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpdateDownloadTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadTaskId': json['downloadTaskId'] == null ? undefined : json['downloadTaskId'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function V1UpdateDownloadTaskRequestToJSON(json: any): V1UpdateDownloadTaskRequest {
    return V1UpdateDownloadTaskRequestToJSONTyped(json, false);
}

export function V1UpdateDownloadTaskRequestToJSONTyped(value?: V1UpdateDownloadTaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'downloadTaskId': value['downloadTaskId'],
        'url': value['url'],
    };
}

