// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//+build !wireinject

package wiring

import (
	"GoLoad/internal/app"
	"GoLoad/internal/configs"
	"GoLoad/internal/dataaccess"
	"GoLoad/internal/dataaccess/cache"
	"GoLoad/internal/dataaccess/database"
	"GoLoad/internal/dataaccess/file"
	"GoLoad/internal/dataaccess/mq/consumer"
	"GoLoad/internal/dataaccess/mq/producer"
	"GoLoad/internal/handler"
	"GoLoad/internal/handler/consumers"
	"GoLoad/internal/handler/grpc"
	"GoLoad/internal/handler/http"
	"GoLoad/internal/handler/jobs"
	"GoLoad/internal/logic"
	"GoLoad/internal/repo"
	"GoLoad/internal/utils"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeStandaloneServer(configFilePath configs.ConfigFilePath) (*app.StandaloneServer, func(), error) {
	config, err := configs.NewConfig(configFilePath)
	if err != nil {
		return nil, nil, err
	}
	configsDatabase := config.Database
	log := config.Log
	logger, cleanup, err := utils.InitializeLogger(log)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := database.InitializeAndMigrateUpDB(configsDatabase, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	goquDatabase := database.InitializeGoquDB(db)
	accountDataAccessor := repo.NewAccountDataAccessor(goquDatabase, logger)
	accountPasswordDataAccessor := repo.NewAccountPasswordDataAccessor(goquDatabase, logger)
	auth := config.Auth
	hash := logic.NewHash(auth)
	configsCache := config.Cache
	client := cache.NewRedisClient(configsCache, logger)
	tokenPublicKey := cache.NewTokenPublicKey(client, logger)
	tokenPublicKeyDataAccessor := repo.NewTokenPublicKeyDataAccessor(goquDatabase, logger)
	token, err := logic.NewToken(accountDataAccessor, tokenPublicKey, tokenPublicKeyDataAccessor, auth, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	account := logic.NewAccount(goquDatabase, accountDataAccessor, accountPasswordDataAccessor, hash, token)
	downloadTaskDataAccessor := repo.NewDownloadTaskDataAccessor(goquDatabase, logger)
	mq := config.MQ
	producerClient, err := producer.NewClient(logger, mq)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	downloadTaskCreatedProducer := producer.NewDownloadTaskCreatedProducer(producerClient, logger)
	download := config.Download
	fileClient, err := file.NewS3Client(download, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cron := config.Cron
	downloadTask := logic.NewDownloadTask(logger, goquDatabase, token, accountDataAccessor, downloadTaskDataAccessor, downloadTaskCreatedProducer, fileClient, cron)
	configsGRPC := config.GRPC
	invalid type, err := grpc.NewHandler(account, downloadTask, configsGRPC)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	server := grpc.NewServer(invalid type)
	httpServer := http.NewServer()
	downloadTaskCreated := consumers.NewDownloadTaskCreated(downloadTask, logger)
	consumerConsumer, err := consumer.NewConsumer(mq, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	root := consumers.NewRoot(downloadTaskCreated, consumerConsumer, logger)
	executeAllPendingDownloadTask := jobs.NewExecuteAllPendingDownloadTask(downloadTask)
	updateDownloadingAndFailedDownloadTaskStatusToPending := jobs.NewUpdateDownloadingAndFailedDownloadTaskStatusToPending(downloadTask)
	standaloneServer := app.NewStandaloneServer(server, httpServer, root, executeAllPendingDownloadTask, updateDownloadingAndFailedDownloadTaskStatusToPending, logger, cron)
	return standaloneServer, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var WireSet = wire.NewSet(configs.WireSet, utils.WireSet, dataaccess.WireSet, logic.WireSet, handler.WireSet, app.WireSet, repo.WireSet,
)

